### ISSUE TITLE
Vote for new package/library name

### ISSUE THREAD

**Issue by mdedetrich** [mdedetrich/scala-json-ast#14]
There are currently to contenders

- scajson
- scajast

Please let me know what you guys prefer, and I will go ahead and change the name of the library as well as the package

**Comment by mdedetrich** [comment]
I am personally in preference of `scajson`, because the package it works nicer with the complete package name (i.e. `scajson.ast`) compared to `scajast.ast`

**Comment by jvican** [comment]
+1 for scalajson!

**Comment by ktoso** [comment]
-1 for `scajast`, it dies not explain that it's json. It also invokes thinking about "hmm, any ast? java ast? wat?"

+1 for `scalajson`, boring name, but fitting and works well with `scalajson.ast`

-0.5 for `scajson` as it seems pretty confusing to how to pronounce it. Sounds a bit like doing a tatoo with a funny name when you're 12 and when you're 30 regretting it that you picked something "that sounded cool back then" ;-)

Hope this helps!

**Comment by farmdawgnation** [comment]
The objection mentioned above to `scajast` is sensible.

It's too bad that we couldn't use `scala.json` because I think that would be perfection. But I, too, can get behind `scalajson`.

**Comment by mdedetrich** [comment]
Okay I think that `scalajson` looks like a good fit. I too would have really liked `scala.json` but looks like that isn't going to happen

**Comment by Ichoran** [comment]
+2 for `scala.json` but failing that, +1 for `scalajson`, +0 for `scajson` and -1 for `scajast`.

**Comment by mdedetrich** [comment]
Okay, I am going to rename it to `scalajson`

**Comment by jvican** [comment]
By the way, for those voting for `scala.json`, [this is the reason](https://contributors.scala-lang.org/t/should-the-scala-platform-modules-use-the-scala-namespace-or-a-common-namespace/422) why we eventually decided not to use the Scala namespace.
