### ISSUE TITLE
Move tests into their own project

### ISSUE THREAD

**Issue by mdedetrich** [mdedetrich/scala-json-ast#18]
This is to prevent the test dependencies showing up in the pox.xml, helpful for @fommil in spray-json. See https://github.com/spray/spray-json/issues/232#issuecomment-312275553

**Comment by fommil** [comment]
It's not for me. It's for the entire community. You'll understand when 2.13.0 is released.

Releasing untested software is not the solution here. You need to rewrite your tests to be zero dependency other than `scala-lang`.

**Comment by mdedetrich** [comment]
> Releasing untested software is not the solution here.

Thats not the idea, the idea is to remove the tests from the pom.xml (travis will be changed so it will always run the tests from the subproject)

> You'll understand when 2.13.0 is released.

Afaik, the major testing frameworks were doing their releases against a prereleased Scala well before the actual release of a Scala major was done for this exact reason. I know that ScalaTest did this.

I mean what is the problem here for you specifically? If its dependencies in the pom.xml, I can still remove it from the POM but enforce tests via sbt. Another option is to use a direct git dependency for tests

**Comment by mdedetrich** [comment]
Also https://github.com/spray/spray-json/blob/master/build.sbt#L23-L27 ?

In fact these are the same test dependencies that ScalaJSON AST uses, scala.js plugin also does not effect the pom.xml for JVM artifacts ( see https://search.maven.org/#artifactdetails%7Corg.scala-lang.platform%7Cscalajson_2.11%7C1.0.0-M2%7Cjar )

**Comment by mdedetrich** [comment]
I am going to close this because @fommil doesn't seem to be entirely consistent with the problem and this appears to be a non issue in reality

- Spray-json also has these same test dependencies (see https://github.com/spray/spray-json/issues/232#issuecomment-312285322)
- Regarding https://github.com/ensime/ensime-server/issues/1821 and https://github.com/ensime/ensime-server/issues/1398, some typelevel projects also contain the same test dependencies as ScalaJSON ast
- We are talking about test dependencies here?

**Comment by fommil** [comment]
I don't want to be involved with this project, please leave me out of it.

**Comment by mdedetrich** [comment]
> I don't want to be involved with this project, please leave me out of it.

Thats why this issue is closed as a non issue 😉
