### ISSUE TITLE
JNumber constructor accepts Float.NaN

### ISSUE THREAD

**Issue by Ichoran** [mdedetrich/scala-json-ast#21]
`Float` should be handled the same way as `Double`.

**Comment by mdedetrich** [comment]
Are you talking about `unsafe`?

**Comment by Ichoran** [comment]
No, the normal one just blithely calls `.toString`, which then throws an exception on `NaN`.  This is different behavior than `Double`, which gives `JNull` instead.

**Comment by mdedetrich** [comment]
Ah yes, I see, thanks will look into it
