### ISSUE TITLE
JNumber has a pointless apply(Short) method

### ISSUE THREAD

**Issue by Ichoran** [mdedetrich/scala-json-ast#23]
There are no cases where `s.toString` is different from `s.toInt.toString` where `s` is a number that could be a short.  Thus, the apply method for shorts is of no benefit.  `Long` is necessary to avoid accidental conversion to `Float`; you can argue `Int` is valuable for speed.  But there is no use for `Short` arguments.  (The only reason these can be helpful is when you're doing a transformation to an unsigned value, or when you need to return the same argument type.)

**Comment by mdedetrich** [comment]
Fixed
