### ISSUE TITLE
Move regex check on JNumber into companion

### ISSUE THREAD

**Issue by sirthias** [mdedetrich/scala-json-ast#28]
Currently the `JNumber` constructor always performs a regex check, even if the argument is known to never fail it (e.g. when it's called from one of the several `JNumber.apply` overloads).

This ticket proposes to mark the `JNumber` case class constructor `private`, add an `JNumber.apply(String)` overload and move the regex check into this method.

Unfortunately this fix depends on two patches to scalac (https://github.com/scala/scala/pull/5730 and https://github.com/scala/scala/pull/5846), which are only available as of Scala 2.11.11 (where it needs the `-Xsource:2.12` flag) and 2.12.2 (no flags required) and thus won't work on Scala 2.10.

Nevertheless I think it'd be a valuable improvement that might also help to (somewhat) alleviate the concerns that @fommil has voiced in #16.

**Comment by mdedetrich** [comment]
Something similar is already being done, will see if I can integrate this. Expect an update within a couple of days

**Comment by fommil** [comment]
you can always do a hand rolled `class`. `case class` is just a boilerplate generator, afterall.

**Comment by mdedetrich** [comment]
I am going to do this in a new PR since it changes source compatibility, I am likely to just use a `class`, no one is going to be using the `JNumber` constructor directly anyways
