### ISSUE TITLE
Fix numericStringEquals with 0 condition

### ISSUE THREAD

**Issue by mdedetrich** [mdedetrich/scala-json-ast#35]
As pointed out by @sirthias, `numericStringEquals` fails on this case `"0" == "-0"`. @Ichoran this should interest you because you are using this equality method in your jsonal library (https://github.com/Ichoran/kse/tree/master/src/main/scala/jsonal)

@sirthias This is seperate to deciding whether or not we should even have `numericStringEquals` (not against removing `numericStringEquals`, its just a seperate issue)

**Comment by mdedetrich** [comment]
Closing this, misinterpreted what @sirthias was saying (I thought it was an actual bug however his complaint is that we do proper number checking)

**Comment by Ichoran** [comment]
Actually, I don't think that case ever comes up in Jsonal because it stores numbers identically equal to `Double` values as `Double`s.
