### ISSUE TITLE
Missing git tags

### ISSUE THREAD

**Issue by dwijnand** [mdedetrich/scala-json-ast#40]
I'm looking for the sources of `"org.mdedetrich" %% "scala-json-ast" % "1.0.0-M6"`. Did you delete the old tags? Could you at least document what SHAs they were associated with?

**Comment by SethTisue** [comment]
my local clone still had the tags:

```
% git tag
1.0.0-M2
1.0.0-M3
1.0.0-M4
1.0.0-M5
1.0.0-M6
1.0.0-M7
1.0.0-M8
% git show -s --oneline 1.0.0-M5 | cat
3e3ae2c ...
% git show -s --oneline 1.0.0-M6 | cat
292020f ...
% git show -s --oneline 1.0.0-M7 | cat
c0bdc31 ...
% git show -s --oneline 1.0.0-M8 | cat
dbbe10b ...
```

**Comment by dwijnand** [comment]
Thanks Seth.

| tag | sha |
|----------|------------------------------------------|
| 1.0.0-M5 | 3e3ae2cfda1037261517077fa047cab8fa97b014 |
| 1.0.0-M6 | 292020fcbb2029ee89bc5d89fd19219e581c1624 |
| 1.0.0-M7 | c0bdc311c6e6f2c5745e1ea0de469b5068f9363d |
| 1.0.0-M8 | dbbe10ba50c23b4dce9d06d28dda5d19d7c0f412 |
